site_name: '芯卓技术'
pages:
- 首页: 'index.md'
- Docker使用例程:
    - '七牛系列': 'docs/qiniu-guide.md'
    - 'Mysql系列': 'docs/supported-devices.md'
    - 'redis系列': 'docs/developer-guide.md'
    - 'mongodb系列': 'docs/opkg.md'
    - 'golang系列': 'docs/build-a-single-package.md'
    - 'beego系列': 'docs/smart-vpn.md'
    - 'nginx系列': 'docs/flashing.md'
    - 'tomcat系列': 'docs/create-opkg-package-repository.md'
    - 'mqtt系列': 'docs/build-beego.md'
    - '翻墙系列': 'docs/create-package.md'
    - '云管理系列': 'docs/build-openwrt-package-using-docker.md'
- 集群例程:
    - 'etcd系列': 'docs/create-gee-app.md'
    - '微服务系列': 'docs/create-gee-app.md'
- Dockerfile描述:
    - '163-nginx': 'docs/create-opkg-package-repository.md'
    - 'beego': 'docs/build-beego.md'
    - 'markdown文档': 'docs/file-business.md'
    - 'dao-ghost文档': 'docs/file-dao-ghost.md'
    - 'firefox文档': 'docs/file-firefox.md'
    - '开关消息文档': 'docs/file-kaiguan.md'
    - 'mkdocker文档': 'docs/file-mkdocker.md'
    - 'mongodb文档': 'docs/file-mongodb-tools.md'
    - 'webshell文档': 'docs/file-shell.md'
    - 'snmp文档': 'docs/file-snmp.md'
    - 'spring-boot文档': 'docs/file-spring-boot.md'
    - 'upload文档': 'docs/file-upload.md'
- Openwrt描述:
    - '固件编译': 'docs/create-openwrt-build.md'    
    - '固件解压打包': 'docs/create-openwrt-image.md'
    - 'ubuntu制作下载': 'docs/create-ubuntun-run.md'   
    - 'Openwrt加载USB': 'docs/openwrt-usb.md'
    - 'ubuntu加载overlayroot': 'docs/ubuntu-overlayroot.md'    
    - 'openvpn说明': 'docs/build-openvpn.md'  
    - 'netifd procd ubus说明': 'docs/create-openwrt-netifd.md' 
    - 'dnsmasq安装': 'docs/create-dnsmas.md' 
    - 'c语言操作uci': 'docs/openwrt-c-uci.md' 
    - 'udp上报路由器': 'docs/openwrt-udpreport.md' 
- 明白活:    
    - '道德经': 'docs/live-daodejing.md'     
     

- 关于我们: 'about.md'
theme: 'flatly'
repo_url: 'http://sinzuo.cn/'
repo_name: '更多'
site_favicon: favicon.ico
google_analytics: ['UA-63908544-1', 'jiang_yi_bo']
copyright: <a rel="nofollow" href="http://sinzuo.cn/">广ICP备15020382号-1</a>
 </br>本文版权归jiang_yi_bo所有，欢迎转载，但未经作者同意必须保留此段声明，且在文章页面明显位置给出原文连接。
    <script type="text/javascript">
        window.zhuge=window.zhuge||[];window.zhuge.methods="_init debug identify track trackLink trackForm page".split(" ");window.zhuge.factory=function(b){return function(){var a=Array.prototype.slice.call(arguments);a.unshift(b);window.zhuge.push(a);return window.zhuge}};for(var i=0;i<window.zhuge.methods.length;i++){var key=window.zhuge.methods[i];window.zhuge[key]=window.zhuge.factory(key)};window.zhuge.load=function(b,x){if(!document.getElementById("zhuge-js")){var a=document.createElement("script");a.type="text/javascript";a.id="zhuge-js";a.async=!0;a.src="";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c);window.zhuge._init(b,x)}};
        window.zhuge.load('f6a2e8eed9e447ea89a63b87763ec7df');
        var duoshuoQuery = {short_name:"openwrtio"}; (function() { var ds = document.createElement('script'); ds.type = 'text/javascript';ds.async = true; ds.src = ''; ds.charset = 'UTF-8'; (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds); })();
    </script>
    
